# NumPy (Numerical Python) - Übung


### Übung 1: 
Erstelle eine Übersicht in der die Gemeinsamkeiten und Unterschiede zwischen Python Listen und NumPy-Array gegenübergestellt werden 

Hinweis: diese Übersicht wird später mit Pandas ergänzt

Hilfestellung: Datentypen, Wie komme ich an ein Element?, Wie ersetze ich ein Element? etc.

### Übung 2:

Übe den Umgang mit NumPy Arrays und werde dadurch sicherer.
 

In [2]:
#Platz für deinen Code

import numpy as np

In [3]:
name = ['Hannah', 'Charlotte', 'Henning', 'Henry', 'Ida']
skills = ['Python', 'Java', 'Python', 'C', 'Python']
experience_level = [1, 2, 2, 3, 3]

In [7]:
# a. Erstelle ein Array (eindimensional) als Konstrukt, welches du im nächsten Schritt mit den Daten befüllst
neues_zeros_array = np.zeros((5), dtype={'names':('name', 'skills', 'experience_level'),'formats':('U10', 'U10', 'i4')})
print("Array mit Nullen:\n", neues_zeros_array)

Array mit Nullen:
 [('', '', 0) ('', '', 0) ('', '', 0) ('', '', 0) ('', '', 0)]


In [18]:
# b. Befülle das Array Konstrukt mit den obigen Daten
neues_zeros_array['name'] = name
neues_zeros_array['skills'] = skills
neues_zeros_array['experience_level'] = experience_level
 
print(neues_zeros_array, type(neues_zeros_array))

[('Hannah', 'Python', 1) ('Charlotte', 'Java', 2) ('Henning', 'Python', 2)
 ('Henry', 'C', 3) ('Ida', 'Python', 3)] <class 'numpy.void'>


In [16]:
# c. Wer steckt hinter dem 2.ten Element?
print(neues_zeros_array[1]['name'])
print(neues_zeros_array[1][0])


Charlotte
Charlotte


In [27]:
# d. Wer kann Python?
print(neues_zeros_array[neues_zeros_array['skills'] == 'Python']['name'])


['Hannah' 'Henning' 'Ida']


In [30]:
# e. Wer kann Python und ist kein Anfänger?
python_experienced = neues_zeros_array[(neues_zeros_array['skills'] == 'Python') & (neues_zeros_array['experience_level'].astype(int) > 1)]
print(python_experienced['name'])  # Namen ausgeben 


['Henning' 'Ida']


### Übung 3

Beispiele für 3D-Arrays 

In [32]:
# Beispiel 1

np_example1  = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
np_example1

array([[[1, 2],
        [3, 4]],

       [[5, 6],
        [7, 8]]])

In [33]:
# Lasse dir die Dimensionen anzeigen
print(np_example1.ndim)

3


In [34]:
# Lasse dir den Shape anzeigen - was sagt der Shape aus?
print(np_example1.shape)
print('                  ')
print('##################')
print('                  ')

print(np_example1)


(2, 2, 2)
                  
##################
                  
[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [37]:
# Beispiel 2

np_example2 = np.array([[[1,2,3], [4,5,6]]])
print(np_example2)

[[[1 2 3]
  [4 5 6]]]


In [36]:
np_example2.shape

(1, 2, 3)

In [41]:
# Greife auf die 3 zu
np_example2[0,0,2]


3

In [45]:
# Greife auf die 5 zu
np_example2[0,1,1]


5

In [46]:
# Beispiel 3

np_example3 = np.array([[[1,2,3], [4,5,6]],[[7,8,9], [10,11,12]],[[13,14,15], [16,17,18]]])
np_example3

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]],

       [[13, 14, 15],
        [16, 17, 18]]])

In [47]:
np_example3.shape 

(3, 2, 3)

In [53]:
# Greife auf die 14 zu
np_example3[2,0,1]
#np_example3[2][0][1]

14

In [57]:
# Greife auf die 9 zu
np_example3[1,0,2]


9

In [80]:
print(np_example3)
np_example3[[0,2],:,2]

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]

 [[13 14 15]
  [16 17 18]]]


array([[ 3,  6],
       [15, 18]])